# Site settings
title: Taylor Martin - Blog
email:
description: "I'm trying to become a professional developer in 12 weeks, and I'm blogging about it."
baseurl: ""
url: "taylormartin.github.io"
twitter_username:
github_username:  taylormartin

# Build settings
markdown: kramdown
permalink: pretty
