# Site settings
title: Taylor Martin
email:
description: "musician, developer, and now...blogger!"
baseurl: ""
url: "taylormartin.github.io"
twitter_username:
github_username:  taylormartin

# Build settings
markdown: kramdown
permalink: pretty
